name: Validate octocov badge commands

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/octocov-badge.yml
      - .octocov.yml

jobs:
  test-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.23.11'
          cache: true

      - name: Build octocov from umatare5/patch-2 branch
        run: |
          git clone --branch umatare5/patch-2 https://github.com/umatare5/octocov.git
          cd ./octocov
          go build
          echo "OCTOCOV_BIN=$(pwd)/octocov" >> "$GITHUB_ENV"

      - name: Show octocov version
        run: |
          "$OCTOCOV_BIN" --version || true

      - name: Generate Go coverage from testdata
        run: |
          cd go-testdata
          go test ./... -coverprofile=../coverage.out

      - name: Case 1-1 > octocov badge coverage
        shell: bash
        run: |
          "$OCTOCOV_BIN" badge coverage

      - name: Case 1-2 > octocov badge coverage --config .octocov.yml
        shell: bash
        run: |
          "$OCTOCOV_BIN" badge coverage --config .octocov.yml

      - name: Case 1-3 > octocov badge coverage --out cover.out
        shell: bash
        run: |
          "$OCTOCOV_BIN" badge coverage --out cover.out && ls cover.out && rm -f cover.out

      - name: Case 1-4 > octocov badge coverage --help
        shell: bash
        run: |
          "$OCTOCOV_BIN" badge coverage --help

      - name: Case 2-1 > octocov badge ratio
        shell: bash
        run: |
          "$OCTOCOV_BIN" badge ratio

      - name: Case 2-2 > octocov badge ratio --config .octocov.yml
        shell: bash
        run: |
          "$OCTOCOV_BIN" badge ratio --config .octocov.yml

      - name: Case 2-3 > octocov badge ratio --out cover.out
        shell: bash
        run: |
          "$OCTOCOV_BIN" badge ratio --out cover.out && ls cover.out && rm -f cover.out

      - name: Case 2-4 > octocov badge ratio --help
        shell: bash
        run: |
          "$OCTOCOV_BIN" badge ratio --help

      - name: Case 3-1 > octocov badge time
        shell: bash
        run: |
          "$OCTOCOV_BIN" badge time
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Case 3-2 > octocov badge time --config .octocov.yml
        shell: bash
        run: |
          "$OCTOCOV_BIN" badge time --config .octocov.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Case 3-3 > octocov badge time --out cover.out
        shell: bash
        run: |
          "$OCTOCOV_BIN" badge time --out cover.out && ls cover.out && rm -f cover.out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Case 3-4 > octocov badge time --help
        shell: bash
        run: |
          "$OCTOCOV_BIN" badge time --help
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
